# Generated by Django 4.0.6 on 2022-07-15 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('imgMain', models.URLField(max_length=300)),
                ('color', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('diet', models.CharField(max_length=500)),
                ('habitat', models.CharField(max_length=500)),
                ('breedingSeason', models.CharField(max_length=50)),
                ('typeOfWater', models.CharField(max_length=50)),
                ('lifeSpan', models.CharField(max_length=200)),
                ('endangeredRating', models.CharField(max_length=50)),
                ('generalInfo', models.CharField(max_length=500)),
            ],
        ),
    ]
