# Generated by Django 4.0.6 on 2022-07-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='breedingSeason',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='color',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='country',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='diet',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='endangeredRating',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='generalInfo',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='habitat',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='lifeSpan',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='region',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='size',
        ),
        migrations.RemoveField(
            model_name='fish',
            name='typeOfWater',
        ),
    ]
