# Generated by Django 4.0.6 on 2022-07-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_hunting'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='avgLength',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fish',
            name='avgLifespan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fish',
            name='avgWeight',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fish',
            name='typeOfWater',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
