# Generated by Django 4.0.6 on 2022-08-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fish_avglength_fish_avglifespan_fish_avgweight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='breedingSeason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fish',
            name='diet',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='fish',
            name='family',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='fish',
            name='habitat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
